pipeline {
  agent none
  // agent {
  //   label 'DevServer'
  // }

  // tools {
  //   maven 'mymaven'
  // }

  stages {
    stage('build') {
      steps {
        sh 'mvn clean package'
      }

      post {
        success {
          archiveArtifacts artifacts: '**/target/*.war'
        }
      }
    }

    stage('test') {
      steps {
        echo "This is Testing stage"
      }
    }

    stage ('deploy') {
      steps {
        echi "Thhis is Deploy stage"
      }
    }
  }
}