pipeline {
  agent any
  // agent NONE
  // agent {
  //   label 'DevServer'
  // }

  environment {
    NAME = "Rajesh"
    ENV = "PROD"
  }

  tools {
    maven 'Maven'
  }

  triggers {
    githubPush()
  }

  parameters {
    string defaultValue: 'Kamireddy', description: 'Default param value', name: 'SurName'
  }

  options {
    retry(5)
    timeout(time: 30, unit: 'SECONDS')
  }

  stages {
    stage('build') {
      steps {
        echo "This is Build stage in $ENV"
        // sh 'mvn clean package'
      }
    }

    stage ('deploy') {
      steps {
        echo "Thhis is Deploy stage ${params.SurName}"
      }
    }

    // Parallel Stage execution
    stage('test') {
      parallel {
        stage('testA'){
          steps {
            echo "This is TestA and Sur name is ${params.SurName}"
          }
        }
        stage('testB'){
          steps{
            echo "This is TestB and Name is $NAME"
          }
        }
      }
      // post {
      //   success {
      //     archiveArtifacts artifacts: '**/target/*.war'
      //   }
      // }
    }
  }
}