pipeline {
  agent any
  // agent NONE
  // agent {
  //   label 'DevServer'
  // }

  tools {
    maven 'Maven'
  }

  triggers {
    githubPush()
  }

  options {
    retry(5)
    timeout(time: 30, unit: 'SECONDS')
  }

  stages {
    stage('build') {
      steps {
        echo "This is Build stage"
        sh 'mvn clean package'
      }

      post {
        success {
          archiveArtifacts artifacts: '**/target/*.war'
        }
      }
    }

    stage('test') {
      steps {
        echo "This is Testing stage"
      }
    }

    stage ('deploy') {
      steps {
        echo "Thhis is Deploy stage"
      }
    }
  }
}